config/routes.rb
Rails.application.routes.draw do
  resources :concepts do
    collection do
      get 'concept_tree'
    end
  end

  post '/rate' => 'rater#create', :as => 'rate'

  resources :instructions
  resources :materials
  devise_for :users

  resources :experiments do
    resources :comments, module: :experiments
    collection do
      get 'order_experiments'
      get 'landing_page'
    end
    member { post :vote }
  end

  root 'experiments#landing_page'

  # The priority is based upon order_number of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  ratyrate_rateable 'name'
  has_attached_file :uploaded_file

  validates_attachment_content_type(
    :uploaded_file,
    content_type: ['image/jpeg', 'image/png', 'image/pdf']
  )

  belongs_to :user

  has_many :comments, as: :commentable
  has_many :experiment_votes
  has_many :materials, dependent: :destroy
  has_many :instructions, dependent: :destroy
  has_many :concepts_experiments
  has_many :concepts, through: :concepts_experiments

  validates :description, :complete_time, :name, :age, presence: true

  # rubocop:disable Metrics/LineLength
  validates :youtube_link, format: {
    allow_blank: true,
    with: %r{\A(?:https?://)?(?:www\.)?youtu(?:\.be|be\.com)/(?:watch\?v=)?([\w-]{10,})\z}
  }, on: :create
  # rubocop:enable Metrics/LineLength

  accepts_nested_attributes_for :experiment_votes
  accepts_nested_attributes_for :materials,
                                reject_if: :all_blank,
                                allow_destroy: true
  accepts_nested_attributes_for :instructions,
                                reject_if: :all_blank,
                                allow_destroy: true

  def self.text_search(query)
    query = query.downcase
    q = "%#{query}%"

    joins(:materials).where(
      'LOWER(name) LIKE ? OR LOWER(description) LIKE ? OR LOWER(item) LIKE ?',
      q,
      q,
      q
    ).uniq
  end

  def self.by_votes
    all.sort_by { |e| e.experiment_votes.count }.reverse
  end

  def self.order_by_mess
    all.sort_by do |e|
      e.average('name').nil? ? 0 : e.average('name').avg
    end.reverse
  end

  def self.order_by_mess_complete_time
    all.sort_by do |e|
      [e.average('name').nil? ? 0 : e.average('name').avg, e.complete_time]
    end.reverse
  end

  # rubocop:disable Metrics/AbcSize
  def self.first_experiment(concept, experiment) # show recommended
    if experiment.concepts.one? && concept.experiments.one?
      return [experiment.concepts.first, experiment_by_votes(experiment)]
    end

    # if current concept doesn't have any more experiments, do this
    unless concept.experiments.pluck(:name).include?(name: experiment.name)
      concept = random_item_without_name(experiment.concepts, concept)
    end

    [concept, random_item_without_name(concept.experiments, experiment)]
  end
  # rubocop:enable Metrics/AbcSize

  def self.second_experiment(concept) # show extended learning
    concept_experiment = []

    random_concept = concept.children.sample if concept.children.any?
    random_concept ||= concept.parents.sample

    random_experiment = random_concept.experiments.sample
    concept_experiment << random_concept << random_experiment
  end

  def self.experiment_by_votes(experiment)
    if Experiment.by_votes[0] != experiment
      Experiment.by_votes[0]
    else
      Experiment.by_votes[1]
    end
  end

  def votes
    read_attribute(:votes) || experiment_votes.sum(:value)
  end

  def return_age
    { 1 => '3 & Under', 2 => '4-6', 3 => '7-9', 4 => '10 & up' }[age]
  end

  def concept_parents
    concepts.flat_map(&:parents).uniq
  end

  def concept_children
    concepts.flat_map(&:children).uniq
  end

  def find_concept
    concepts.sample
  end

  private_class_method def self.random_item_without_name(collection, object)
    collection.where.not(name: object.name).sample
  end
end

app/controllers/experiments/comments_controller.rb
module Experiments
  class CommentsController < CommentsController
    before_action :set_commentable

    private

    def set_commentable
      @commentable = Experiment.find(params[:experiment_id])
    end
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_filter :authenticate_user!,
                except: %i[index show vote landing_page order_experiments]
  before_action :set_experiment, only: %i[show edit update destroy vote]

  # GET /experiments
  # GET /experiments.json
  def landing_page
    @concepts = Concept.all
  end

  def index
    if params[:query]
      @experiments = Experiment.text_search(params[:query]).all.by_votes
      flash.now[:notice] = 'No items found' if @experiments.empty?
    else
      @experiments = Experiment.all.by_votes
    end
  end

  def order_experiments
    if params[:queryValue] && params[:selectValue] == '1'
      @experiments = sort_experiments(:age)
    elsif params[:queryValue] && params[:selectValue] == '2'
      @experiments = sort_experiments(:complete_time)
    end
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
    @parents  = @experiment.concept_parents
    @children = @experiment.concept_children
    @concept  = @experiment.find_concept

    set_concepts_and_experiments

    @comment = Comment.new
    @top_experiment = Experiment.experiment_by_votes(@experiment)
  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
    @experiment.materials.build
    @experiment.instructions.build
  end

  # GET /experiments/1/edit
  def edit; end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(experiment_params)

    if valid_concepts? && @experiment.save
      @experiment.concepts << Concept.find(params[:concepts])
      flash[:notice] = 'Experiment was successfully created.'
      return redirect_to @experiment
    end

    render :new
  end

  # PATCH/PUT /experiments/1
  # PATCH/PUT /experiments/1.json
  def update
    if @experiment.update(experiment_params)
      redirect_to @experiment, notice: 'Experiment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment.destroy
    respond_to do |format|
      format.html do
        flash[:notice] = 'Experiment was successfully destroyed.'
        redirect_to experiments_url
      end
    end
  end

  def vote
    vote = current_user.experiment_votes.new(
      value: params[:value],
      experiment_id: params[:id]
    )
    if vote.save
      redirect_to :back, notice: 'Thank you for voting.'
    else
      redirect_to :back, alert: 'Unable to vote; perhaps you already did.'
    end
  end

  private

  def sort_experiments(attr)
    experiments_from_text_search.sort_by do |e|
      [e.send(attr), -1 * e.experiment_votes.count]
    end
  end

  def experiments_from_text_search
    Experiment.text_search(params[:queryValue]).all
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_experiment
    @experiment = Experiment.find(params[:id])
  end

  def set_concepts_and_experiments
    first_experiment  = Experiment.first_experiment(@concept, @experiment)
    second_experiment = Experiment.second_experiment(@concept)

    @first_concept     = first_experiment[0]
    @first_experiment  = first_experiment[1]
    @second_concept    = second_experiment[0]
    @second_experiment = second_experiment[1]
  end

  def valid_concepts?
    return true if params[:concepts].present?
    flash.now[:notice] = 'You must select a Concept for your Experiment.'
    false
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  # rubocop:disable Metrics/MethodLength
  def experiment_params
    params.require(:experiment).permit(
      :name,
      :description,
      :youtube_link,
      :complete_time,
      :uploaded_file,
      :age,
      materials_attributes: %i[id experiment_id item _destroy],
      instructions_attributes: %i[
        id
        experiment_id
        information
        order_number
        _destroy
      ],
      experiment_votes: %i[id value experiment_id],
      concepts_attributes: %i[experiment_id name description_link video_link]
    ).merge(user_id: current_user.id)
  end
  # rubocop:enable Metrics/MethodLength
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
  def embed(youtube_url)
    youtube_id = youtube_url.split('=').last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end

  def find_unique_experiment(exp_one, exp_two, exp_three)
    Experiment.where.not(name: [exp_one, exp_two, exp_three]).by_votes.first
  end
end

app/views/experiments/_experiments.html.erb
<div class="exp-index-container">
  <div class="index-header">
    <% if params[:query] %>
      <h1 class="search-results-title">Search Results for: <%= params[:query] %></h1>
    <% else %>
      <h1 class="index-title">All Experiments</h1>
    <% end %>

    <span class="sort">
      <select size="1" id="order" class="order">
        <option value="">Sort By</option>
        <option value="1">Age</option>
        <option value="2">Time</option>
      </select>
    </span>
  </div>

  <div class="index-wrapper">
    <% @experiments.each do |experiment| %>
      <div class="index-experiment-card">
        <% if experiment.uploaded_file.blank? %>
          <a href="<%= url_for experiment %>" class="index-photo" style="background-image: url(<%= image_path 'bubbles.jpg' %>)"></a>
        <% else %>
          <a href="<%= url_for experiment %>" class="index-photo" style="background-image: url('<%= experiment.uploaded_file %>')"></a>
        <% end %>
          <span class="index-exp-title-bar">
            <h3 class="index-exp-title"><%= experiment.name %></h3>
            <i class="fa fa-thumbs-up index-likes"> <%= pluralize experiment.votes, 'like' %></i>
          </span>
        </a>

        <div class="index-info">
          <div class="index-exp-ratings">
            <span class="ratings-container">
              <span class="index-concept-icon">
                <% c = experiment.concepts.sample %>
                <%= image_tag "#{c.name}.png", class: 'concept-img-small' %><br>
                <%= link_to c.name, concept_path(c) %>
              </span>

              <div class="index-time">
                <%= image_tag 'time.png', class: 'icon-small' %><br>
                <%= experiment.complete_time %> hour(s)
              </div>

              <div class="index-age">
                <%= image_tag 'age.png', class: 'icon-small' %><br>
                Ages <%= experiment.return_age %>
              </div>

              <div class="mess-rate-disable index-mess">
                <%= rating_for experiment, 'name', star_path: '/images/ratyrate', disable_rate: true %>
                <br>
                Mess
              </div>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/experiments/_form.html.erb
<%= form_for @experiment, html: { multipart: true } do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@experiment.errors.count, 'error') %> prohibited this experiment from being saved:
      </h2>

      <ul>
        <% @experiment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="cover">
    <% if @experiment.uploaded_file.blank? %>
      <div class="show-exp-image" style="background-image: url(<%= image_path 'bubbles.jpg' %>)"></div>
    <% else %>
      <div class="show-exp-image" style="background-image: url(<%= image_path @experiment.uploaded_file %>)">
      </div>
    <% end %>
  </div>

  <div class="largest-new-container">
    <div class="new-exp-title-bar">
      <% if params[:action] == 'edit' %>
        <h1 class="new-exp-title">Edit Experiment</h1>
      <% else %>
        <h1 class="new-exp-title">Add New Experiment</h1>
      <% end %>
    </div>

    <div class="new-container">
      <div class="experiment">
        <div class="form-container">
          <p class="required"><i class="fa fa-asterisk"></i> = required</p>
          <div class="new-basics">
            <div class="field new-exp-name">
              <label>Experiment Name *</label><br>
              <%= f.text_area :name, cols: 100, rows: 2 %>
            </div>

            <div class="field new-description">
              <label>Description </label>
              <small> (Please include 2-3 sentences to describe the purpose of this experiment.) *</small>
              <%= f.text_area :description, cols: 100, rows: 2 %>
            </div>
          </div>

          <div class="new-media">
            <div class="field new-photo">
              <label>Upload a Photo *</label><br>
              <%= f.file_field 'uploaded_file', id: 'pictureInput', rows: 2 %>
            </div>
            <div id="target"></div>
            <div class="field new-youtube">
              <label>Link To YouTube Tutorial</label><br>
              <%= f.url_field :youtube_link, class: 'tutorial-link' %>
            </div>
          </div>

          <div class="field new-time">
            <label>Time Expected to Complete *</label><br>
            <%= f.number_field(:complete_time, in: 1..20, step: 1) %> hours
          </div>

          <div class="field new-years">
            <label>What age range works best? *</label><br>
            <span class="age-dropdown">
              <%=
                f.select(
                  :age,
                  options_for_select([['Under 3', 1], ['4-6',2], ['7-9',3], ['10 & up', 4]]),
                  { prompt: 'Age Ranges' }
                )
              %>
            </span>
          </div>

          <div class="new-mess">
            <label>On a scale of 1 to 5, how messy is this experiment?</label><br>
            <%=
              rating_for(
                @experiment,
                'name',
                star_path: '/images/ratyrate',
                disable_rate: true
              )
            %>
            <br>
          </div>

          <span class="new-exp-concept">
            <label>Which concepts apply to this experiment? *</label><br>
            <div class="concept-section">
              <% Concept.all.find_each do |concept| %>
                <div class="single-concept">
                  <% if @experiment.concepts.include?(concept) %>
                    <%=
                      check_box_tag(
                        "concepts[#{concept.id}]",
                        concept.id,
                        true,
                        class: 'concept-checkbox'
                      )
                    %>
                    <label for="concepts_<%= concept.id %>" class="concept-checkbox-label">
                      <%= concept.name %>
                    </label>
                  <% else %>
                    <%=
                      check_box_tag(
                        "concepts[#{concept.id}]",
                        concept.id,
                        false,
                        class: 'concept-checkbox'
                      )
                    %>
                    <label for="concepts_<%= concept.id %>" class="concept-checkbox-label">
                      <%= concept.name %>
                    </label>
                  <% end %>
                </div>
              <% end %>
            </div>
          </span>

          <br>

          <div class="new-materials">
            <ul class="field unordered-list-materials">
              <label>Materials *</label><br>
              <%= f.fields_for(:materials) do |ff| %>
                <li>
                  <div class="field material">
                    <%= ff.text_field :item, class: 'new-material' %>
                    <% if current_page?(new_experiment_path) || params[:action] == 'create' %>
                      <button type="button" class="delete-material-btn">
                        <i class="fa fa-trash"></i>
                      </button>
                    <% else %>
                      <div class="delete-checkbox">
                        <%= ff.check_box :_destroy, class: 'destroy' %>
                        <%= ff.label 'Delete', class: 'destroy-label' %>
                      </div>
                    <% end %>
                  </div>
                </li>
              <% end %>
            </ul>
            <button type="button" class="add-material-btn">
              <i class="fa fa-plus"></i> Add New Material
            </button>
          </div>

          <div class="new-instructions">
            <ul class="field unordered-list-instructions">
              <label>Instructions *</label><br>
              <%= f.fields_for(:instructions) do |ff| %>
                <li>
                  <div class="instruction-fields">
                    <div class="field instruction">
                      <%= ff.text_field :information, class: 'new-instruction' %>
                      <% if current_page?(new_experiment_path) || params[:action] == 'create' %>
                        <button type="button" class="delete-instruction-btn">
                          <i class="fa fa-trash"></i>
                        </button>
                      <% else %>
                        <%= ff.label 'Delete', class: 'destroy-label' %>
                        <%= ff.check_box :_destroy, class: 'destroy'%>
                      <% end %>
                    </div>
                  </div>
                </li>
              <% end %>
            </ul>

            <button type="button" class="add-instruction-btn">
              <i class="fa fa-plus"></i> Add Next Step
            </button>
          </div>

          <div class="actions new-exp-btn">
            <% if current_page?(new_experiment_path) || params[:action] == 'create' %>
              <%= f.submit 'Create Experiment', data: { disable_with: 'Please wait...' } %>
            <% elsif params[:action] == 'edit' %>
              <%= f.submit 'Update Experiment', data: { disable_with: 'Please wait...' } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/experiments/_instructions.html.erb
<div class="panel panel-default" data-id="<%= instruction.order_number %>">
  <%= instruction.order_number %> | <%= instruction.information %><br>
</div>

app/views/experiments/_order_experiments.html.erb
<div class="index-wrapper">

<% experiments.each do |experiment| %>

<div class="index-experiment-card">
  <% if experiment.uploaded_file.blank? %>
    <a href="<%= url_for experiment %>" class="index-photo" style="background-image: url(<%= image_path "bubbles.jpg" %>)">
  <% else %>
    <a href="<%= url_for experiment %>" class="index-photo" style="background-image: url('<%= experiment.uploaded_file %>')">
  <% end %>
    <span class="index-exp-title-bar"><h3 class="index-exp-title"><%= experiment.name %></h3>

      <i class="fa fa-thumbs-up index-likes"> <%= pluralize experiment.votes, "like" %></i>
    </span>
  </a>

  <div class="index-info">
    <div class="index-exp-ratings">
      <span class="ratings-container">
        <span class="index-concept-icon">
          <% c = experiment.concepts.sample %>
          <%= image_tag "#{c.name}.png", class: "concept-img-small" %><br>
          <%= link_to c.name, concept_path(c) %>
        </span>

        <div class="index-time">
          <%= image_tag "time.png", class: "icon-small" %><br>
          <%= experiment.complete_time %> hour(s)
        </div>

        <div class="index-age">
          <%= image_tag "age.png", class: "icon-small" %><br>
          Ages <%= experiment.return_age %>
        </div>

        <div class="mess-rate-disable index-mess">
          <%= rating_for experiment, "name", star_path: '/images/ratyrate', :disable_rate => true %><br>
          Mess
        </div>
      </span>
    </div>
  </div>
</div>
<% end %>
</div>

app/views/experiments/_ordered_experiments.html.erb
<div class="index-wrapper">
  <% experiments.each do |experiment| %>
    <div class="index-experiment-card">
      <%
        if experiment.uploaded_file.blank?
          url = image_path 'bubbles.jpg'
        else
          url = "'#{experiment.uploaded_file}'"
        end
      %>

      <a href="<%= url_for experiment %>" class="index-photo" style="background-image: url(<%= url %>)">
        <span class="index-exp-title-bar">
          <h3 class="index-exp-title"><%= experiment.name %></h3>
          <i class="fa fa-thumbs-up index-likes"> <%= pluralize experiment.votes, 'like' %></i>
        </span>
      </a>

      <div class="index-info">
        <div class="index-exp-ratings">
          <span class="ratings-container">
            <span class="index-concept-icon">
              <% c = experiment.concepts.sample %>
              <%= image_tag "#{c.name}.png", class: 'concept-img-small' %><br>
              <%= link_to c.name, concept_path(c) %>
            </span>

            <div class="index-time">
              <%= image_tag 'time.png', class: 'icon-small' %><br>
              <%= experiment.complete_time %> hour(s)
            </div>

            <div class="index-age">
              <%= image_tag 'age.png', class: 'icon-small' %><br>
              Ages <%= experiment.return_age %>
            </div>

            <div class="mess-rate-disable index-mess">
              <%= rating_for experiment, 'name', star_path: '/images/ratyrate', disable_rate: true %><br>
              Mess
            </div>
          </span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/experiments/edit.html.erb
<%= render 'form' %>

app/views/experiments/index.html.erb
<%= render 'experiments' %>

app/views/experiments/landing_page.html.erb
<div id="landing">
  <div id="bg">
    <div class="landing-intro">
      <h1 class="landing-logo">stempirical</h1>

      <p class="stempirical-tagline">share the wonder</p>
      <div class="landing-search">
        <%= form_tag experiments_path, method: 'get', id: 'landing-search-form' do %>
          <%=
            text_field_tag(
              'query',
              params[:query],
              placeholder: 'Search Experiments',
              class: 'landing-exp-search'
            )
          %>
          <button class="fa fa-search landing-fa-search"></button>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="initial-suggested">
  <div class="suggested-container">
    <% used_experiments = [] %>
    <% ['Observation', 'Plants', 'Molecular Behavior'].each_with_index do |s, index| %>
      <%
        concept = @concepts.find_by(name: s)
        if index == 0
          experiment = concept.experiments.sample
        elsif index == 1
          experiment = concept.experiments.where.not(name: "#{used_experiments[0]}").sample
        else
          experiment = concept.experiments.where.not(name: "#{used_experiments[1]}").sample
        end
        used_experiments << experiment.name
      %>

      <div class="suggested">
        <div class="suggested-exp-title-bar">
          <div class="suggested-exp-title">
            <%= link_to experiment.name, experiment_path(experiment) %>
          </div>
          <i class="fa fa-thumbs-up suggested-likes">
            <%= pluralize experiment.votes, 'like' %>
          </i>
        </div>

        <div class="suggested-img">
          <% if experiment.uploaded_file.blank? %>
            <a href="<%= url_for experiment %>" class="suggested-exp-img" style="background-image: url(<%= image_path 'bubbles.jpg' %>)"></a>
          <% else %>
            <a href="<%= url_for experiment %>" class="suggested-exp-img" style="background-image: url('<%= experiment.uploaded_file %>')"></a>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="suggested">
      <div class="suggested-exp-title-bar">
        <div class="suggested-exp-title">
          <% top_experiment = find_unique_experiment(*used_experiments) %>
          <%= link_to top_experiment.name, experiment_path(top_experiment) %>
        </div>
        <i class="fa fa-thumbs-up suggested-likes">
          <%= pluralize top_experiment.votes, 'like' %>
        </i>
      </div>

      <div class="suggested-img">
        <% if top_experiment.uploaded_file.blank? %>
          <a href="<%= url_for top_experiment %>" class="suggested-exp-img" style="background-image: url(<%= image_path 'bubbles.jpg' %>)"></a>
        <% else %>
          <a href="<%= url_for top_experiment %>" class="suggested-exp-img" style="background-image: url('<%= top_experiment.uploaded_file %>')"></a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/experiments/new.html.erb
<header></header>

<%= render 'form' %>

app/views/experiments/order_experiments.js.erb
$(".index-wrapper").replaceWith("<%= j(render partial:  'experiments/ordered_experiments', locals: { experiments: @experiments }) %>");
initStars();