config/routes.rb
Rails.application.routes.draw do
  resources :concepts do
    collection do
      get 'concept_tree'
    end
  end

  post '/rate' => 'rater#create', :as => 'rate'

  resources :instructions
  resources :materials
  devise_for :users

  resources :experiments do
    resources :comments, module: :experiments
    collection do
      get 'order_experiments'
      get 'landing_page'
    end
    member { post :vote }
  end

  root 'experiments#landing_page'

  # The priority is based upon order_number of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head><%= favicon_link_tag 'favicon.ico2' %>
    <title>stempirical</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <% if Rails.env.development? %>
      <%= javascript_include_tag 'tota11y' %>
    <% end %>
  </head>

  <body>
    <header class="nav-bar">

    <h1 class="logo"><%= link_to_unless_current('stempirical', root_path) %></h1>
      <div class="search">
        <%= form_tag experiments_path, method: 'get', id: 'search-form' do %>
          <%=
            text_field_tag(
              'query',
              params[:query],
              placeholder: 'Search Experiments',
              class: 'exp-search'
            )
          %>
          <button class="fa fa-search nav-fa-search"></button>
        <% end %>
      </div>

      <div class="nav-links">
        <div class="nav-link <%= 'active' if current_page?(concept_tree_concepts_path) %>">
          <%= link_to 'Concept Tree', concept_tree_concepts_path %>
        </div>
        <div class="nav-link <%= 'active' if current_page?(experiments_path) || params[:action] == 'show'  %>">
          <%= link_to 'All Experiments', experiments_path %>
        </div>
        <div class="nav-link <%= 'active' if current_page?(new_experiment_path) %>">
          <%= link_to 'Add My Experiment', new_experiment_path %>
        </div>
        <div class="nav-link">
          <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Login', new_user_session_path %> | <%= link_to 'Sign Up', new_user_registration_path %>
          <% end %>
        </div>
      </div>
    </header>

    <div class="main-content">
      <% if notice || alert %>
        <div class="messages">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>